        </div>
    </div>
</div>

<footer id="Footer" class="clearfix">
    <div class="copyright">
        © {{ now|date('Y') }} {{ 'company_name'|env }}. All Rights Reserved.
    </div>

</footer>

<script src="{{ 'plugins/jquery/jquery-1.11.3.min.js'|asset }}"></script>
<script src="{{ 'plugins/bootstrap/js/bootstrap.min.js'|asset }}"></script>
<script src="{{ 'plugins/jquery-ui/jquery-ui-1.10.3.min.js'|asset }}"></script>
<script src="{{ 'plugins/jquery-validate/jquery.validate.js'|asset }}"></script>
<script src="{{ 'plugins/jquery-validate/additional-methods.js'|asset }}"></script>
<script src="{{ 'plugins/masked-input/jquery.maskedinput.min.js'|asset }}"></script>
<script src="{{ 'plugins/bootstrap-timepicker/bootstrap-timepicker.min.js'|asset }}"></script>
<script src="{{ 'js/app.js'|asset }}"></script>
</body>
</html>