<!DOCTYPE html>
<html class="no-js" lang="en-US" itemscope="itemscope" itemtype="https://schema.org/WebPage">

<!-- head -->
<head>

    <!-- meta -->
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <title itemprop="name">Reservation | Black Coach Limousine</title>

    <link rel='stylesheet' id='open-sans-css'  href='https://fonts.googleapis.com/css?family=Open+Sans%3A300italic%2C400italic%2C600italic%2C300%2C400%2C600&#038;subset=latin%2Clatin-ext&#038;ver=292e1b81aed3b09123cb8597bf09f835' type='text/css' media='all' />

    <link rel="stylesheet" href="{{ 'plugins/bootstrap/css/bootstrap.min.css'|asset }}" type="text/css" media="screen" />
    <link rel="stylesheet" href="{{ 'plugins/fontawesome/css/font-awesome.min.css'|asset }}" type="text/css" media="screen"/>
    <link rel="stylesheet" href="{{ 'css/layout.css'|asset }}" type="text/css" media="screen"/>
    <link rel="stylesheet" href="{{ 'css/app.css'|asset }}" type="text/css" media="screen"/>
    <style>
        body {
            font-family: "Open-sans", sans-serif;
            background: {{ 'body_bg_color'|env }}!important;
            color: {{ 'body_tx_color'|env }}!important;
        }
        label {
            color: {{ 'body_tx_color'|env }}!important;
        }

        .copyright {
            padding: 30px;
            color: #FFF;
            min-height: 33px;
            background-color: #444;
            text-align: center;
        }
        .modal {
            color: #000;
        }
        header {
            width: 100%;
            float: left;
        }

        header .logo {
            padding: 30px;
        }


        a {
            color: {{ 'link_tx_color'|env }};
        }

        .btn, .back a {
            float: right;
            background-color: {{ 'btn_bg_color'|env }};
            color: {{ 'btn_tx_color'|env }};
            padding: 5px 10px;
            margin-top: 40px;
            border: 0px;
            border-radius: 0px;
            -webkit-border-radius: 0px;
            -moz-border-radius: 0px;
            box-shadow: none;
            -moz-box-shadow: none;
            -webkit-box-shadow: none;
        }

        .btn:hover, .back a:hover {
            background-color: {{ 'btn_h_bg_color'|env }};
            color: {{ 'btn_h_tx_color'|env }};
            text-decoration: none;
            border: 0px;
        }

        #subheader h1.title {
            font-size: 30px;
            font-weight: bold;
            letter-spacing: .01em;
        }

        @media screen and (max-width: 767px) {
            .back a {
                top: 34px;
                position: relative;
                margin-top: 0px;
            }

            header .logo {
                padding-top: 30px;
                padding-bottom: 0px;
                text-align: center;
            }

            input[type="submit"] {
                margin-top: 50px;
                float: none!important;
                width: 100%;
            }
        }

        .smart-form fieldset {
            background: {{ 'body_bg_color'|env }}!important;
        }

        label.radio, label.checkbox {
            color: {{ 'body_tx_color'|env }}!important;
        }
    </style>
</head>

<body>
<div id="Wrapper">
    <div class="container" >
        <header>
            <div class="row">
                <div class="logo col-sm-6">
                    <img src="{{ 'company_logo'|env }}" style="max-width: 200px"/>
                </div>
                <div class="back col-sm-6">
                    <a href="{{ 'company_website'|env }}">Go Back to Main site</a>
                </div>
            </div>
        </header>

        <div id="subheader">
            <h1 class="title">Reservation</h1>
        </div>
    </div>
    <div id="Content">
        <div class="container">